---
version: '0.2'
language: en, vi
ignorePaths:
  - '**/node_modules/**'
  - '**/.git/**'
  - '**/.github/**'
  - '**/.vscode/**'
  - '**-data/**'
dictionaryDefinitions:
  - {name: custom-words, path: ./dictionary/custom-words.txt}
dictionaries:
  - custom-words
  - typescript
  - node
  - npm
  - python
  - cpp
  - bash
  - json
  - html
  - css
  - yaml
  - lua
