require('nvim-treesitter.configs').setup({
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  ensure_installed = {
    'lua',
    'query',
    'git_rebase',
    'diff',
    'gitcommit',
    'git_config',
    'css',
    'jsdoc',
    'json',
    'jsonc',
    'luadoc',
    'toml',
    'regex',
    'bash',
    'html',
    'javascript',
    'luap',
    'markdown',
    'markdown_inline',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'xml',
    'yaml',
  },
  auto_install = true,
})

require('treesitter-context').setup()
